#!/usr/bin/env python3
r"""Analyze WAVE PDFs/corpus rows generated by wave_260709_meeting_campaign.py.

Typical flow from C:\...\AquaNova\code\scripts:

    python .\wave_260709_meeting_analyze.py --export-corpus --print-summary

This script uses the existing V81 corpus exporter when available, then filters
for PDFs whose names start with V100_MTG_260709.  It does not parse PDFs itself;
it reuses the established WAVE report corpus pipeline.
"""
from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

IMPORTANT_COLUMNS = [
    "pdf_name",
    "process",
    "design_warnings",
    "system.feed_flow_m3h",
    "system.product_flow_m3h",
    "system.recovery_pct",
    "system.specific_energy_kwh_m3",
    "system.product_tds_mgL",
    "pass.feed_pressure_bar",
    "pass.average_flux_lmh",
    "pass.final_concentrate_tds_mgL",
    "ccro.pf_feed_ratio_pct",
    "ccro.pf_feed_flow_m3h_per_pv",
    "ccro.pf_concentrate_flow_m3h_per_pv",
    "ccro.pf_sequence_duration_min",
    "ccro.cc_sequence_duration_min",
    "ccro.complete_cycle_duration_min",
]


def _scripts_dir() -> Path:
    return Path(__file__).resolve().parent


def _project_root() -> Path:
    sd = _scripts_dir()
    return sd.parent if sd.name.lower() == "scripts" else sd


def _wave_records_dir() -> Path:
    return _scripts_dir() / "wave_records"


def _latest_corpus_csv(report_dir: Path) -> Path | None:
    candidates = sorted(report_dir.glob("wave_report_corpus_*.csv"), key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0] if candidates else None


def _run_corpus_export(results_dir: Path) -> None:
    exporter = _wave_records_dir() / "wave_v81_report_corpus_export.py"
    if not exporter.exists():
        raise FileNotFoundError(f"V81 corpus exporter not found: {exporter}")
    cmd = [sys.executable, str(exporter), "--results-dir", str(results_dir), "--print-summary"]
    print("running: " + " ".join(str(x) for x in cmd))
    subprocess.run(cmd, check=True)


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def _write_csv(path: Path, rows: list[dict[str, Any]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def _classify(pdf_name: str) -> str:
    name = pdf_name.upper()
    if "_FR" in name:
        return "fr_pump_energy"
    if "_FLUX_" in name:
        return "flux_push"
    if "_TDS" in name:
        return "raw_tds_safety"
    if "2PASS" in name or "R95" in name:
        return "high_recovery_stress"
    return "meeting_260709"


def _to_float(x: Any) -> float | None:
    try:
        if x is None or str(x).strip() == "" or str(x).lower() == "nan":
            return None
        return float(str(x).replace(",", ""))
    except Exception:
        return None


def _annotate(rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    annotated: list[dict[str, Any]] = []
    for row in rows:
        pdf = row.get("pdf_name", "")
        out: dict[str, Any] = {col: row.get(col, "") for col in IMPORTANT_COLUMNS}
        out["meeting_group"] = _classify(pdf)
        warnings = str(row.get("design_warnings", "") or "")
        out["has_pf_feed_ratio_warning"] = "PF Feed Ratio" in warnings
        out["has_flux_or_recovery_warning"] = any(token in warnings for token in ["Flux", "Recovery", "Permeate Flow", "Maximum Limit"])
        out["has_pressure_warning"] = "Pressure" in warnings
        pf_ratio = _to_float(row.get("ccro.pf_feed_ratio_pct"))
        sec = _to_float(row.get("system.specific_energy_kwh_m3"))
        flux = _to_float(row.get("pass.average_flux_lmh"))
        pressure = _to_float(row.get("pass.feed_pressure_bar"))
        out["actual_pf_feed_ratio_pct"] = "" if pf_ratio is None else pf_ratio
        out["sec_kwh_m3_numeric"] = "" if sec is None else sec
        out["flux_lmh_numeric"] = "" if flux is None else flux
        out["feed_pressure_bar_numeric"] = "" if pressure is None else pressure
        annotated.append(out)
    return annotated


def _summary(rows: list[dict[str, Any]]) -> dict[str, Any]:
    groups: dict[str, int] = {}
    warning_counts: dict[str, int] = {"pf_feed_ratio": 0, "flux_or_recovery": 0, "pressure": 0}
    for row in rows:
        group = str(row.get("meeting_group", "unknown"))
        groups[group] = groups.get(group, 0) + 1
        if row.get("has_pf_feed_ratio_warning"):
            warning_counts["pf_feed_ratio"] += 1
        if row.get("has_flux_or_recovery_warning"):
            warning_counts["flux_or_recovery"] += 1
        if row.get("has_pressure_warning"):
            warning_counts["pressure"] += 1
    return {
        "schema_version": "aquanova.wave_meeting_260709_analysis.v100",
        "row_count": len(rows),
        "group_counts": groups,
        "warning_counts": warning_counts,
    }


def _write_markdown(path: Path, rows: list[dict[str, Any]], summary: dict[str, Any]) -> None:
    lines = [
        "# 2026-07-09 WAVE meeting test analysis",
        "",
        "```json",
        json.dumps(summary, ensure_ascii=False, indent=2),
        "```",
        "",
        "| PDF | Group | SEC | Feed pressure | Flux | PF Feed Ratio | Warnings |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        warn_bits = []
        if row.get("has_pf_feed_ratio_warning"):
            warn_bits.append("PF ratio")
        if row.get("has_flux_or_recovery_warning"):
            warn_bits.append("flux/recovery")
        if row.get("has_pressure_warning"):
            warn_bits.append("pressure")
        lines.append(
            f"| {row.get('pdf_name','')} | {row.get('meeting_group','')} | "
            f"{row.get('sec_kwh_m3_numeric','')} | {row.get('feed_pressure_bar_numeric','')} | "
            f"{row.get('flux_lmh_numeric','')} | {row.get('actual_pf_feed_ratio_pct','')} | "
            f"{', '.join(warn_bits) if warn_bits else '-'} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze WAVE corpus rows for the 2026-07-09 meeting cases.")
    parser.add_argument("--results-dir", default=None, help="WAVE results dir. Default: ./wave_records/results from scripts dir.")
    parser.add_argument("--corpus-csv", default=None, help="Existing V81 corpus CSV. If omitted, latest under _report_corpus is used.")
    parser.add_argument("--export-corpus", action="store_true", help="Run V81 corpus exporter before analysis.")
    parser.add_argument("--print-summary", action="store_true")
    args = parser.parse_args()

    results_dir = Path(args.results_dir).resolve() if args.results_dir else _wave_records_dir() / "results"
    report_dir = results_dir / "_report_corpus"
    if args.export_corpus:
        _run_corpus_export(results_dir)
    corpus_csv = Path(args.corpus_csv).resolve() if args.corpus_csv else _latest_corpus_csv(report_dir)
    if not corpus_csv or not corpus_csv.exists():
        raise FileNotFoundError("No corpus CSV found. Run with --export-corpus first.")

    rows = _read_csv(corpus_csv)
    meeting_rows = [row for row in rows if str(row.get("pdf_name", "")).startswith("V100_MTG_260709")]
    annotated = _annotate(meeting_rows)
    out_base = corpus_csv.with_name(corpus_csv.stem + "_meeting_260709_analysis")
    out_csv = out_base.with_suffix(".csv")
    out_md = out_base.with_suffix(".md")
    out_json = out_base.with_suffix(".json")
    columns = [
        "pdf_name",
        "meeting_group",
        "process",
        "system.feed_flow_m3h",
        "system.product_flow_m3h",
        "system.recovery_pct",
        "sec_kwh_m3_numeric",
        "feed_pressure_bar_numeric",
        "flux_lmh_numeric",
        "actual_pf_feed_ratio_pct",
        "ccro.pf_feed_flow_m3h_per_pv",
        "ccro.pf_sequence_duration_min",
        "has_pf_feed_ratio_warning",
        "has_flux_or_recovery_warning",
        "has_pressure_warning",
        "design_warnings",
    ]
    s = _summary(annotated)
    _write_csv(out_csv, annotated, columns)
    out_json.write_text(json.dumps({"summary": s, "rows": annotated}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    _write_markdown(out_md, annotated, s)
    print(f"meeting analysis csv: {out_csv}")
    print(f"meeting analysis json: {out_json}")
    print(f"meeting analysis markdown: {out_md}")
    if args.print_summary:
        print("summary=" + json.dumps(s, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
