#!/usr/bin/env python3
r"""Generate WAVE test plans for the 2026-07-09 pilot HRRO/CCRO discussion using LG BW 440 R G2.

Run from the AquaNova scripts directory:

    cd C:\Users\a\Desktop\프로젝트\AquaNova\code\scripts
    python .\wave_lg_bw440_pilot_campaign.py --write --print-summary --print-run-commands

Important WAVE catalog note:
    WAVE is a DuPont tool.  If your installed WAVE catalog cannot select
    "LG BW 440 R G2", regenerate the same pilot geometry with a WAVE-selectable
    8-inch 440 ft2 brackish surrogate:

    python .\wave_lg_bw440_pilot_campaign.py --write --wave-element "FilmTec™ BW30-440i" --print-summary --print-run-commands

The case metadata still records the actual installed membrane as LG BW 440 R G2.
"""
from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

SCHEMA_VERSION = 1
PLAN_VERSION = "V102_260709_LG_BW440"

# Actual pilot membrane information supplied from the 2026-07-09 discussion.
ACTUAL_MEMBRANE = {
    "brand": "LG Chem",
    "model": "LG BW 440 R G2",
    "application": "Brackish Water Reverse Osmosis Membrane",
    "average_nacl_rejection_pct": 99.78,
    "max_pressure_bar": 41.4,
    "max_pressure_psi": 600,
    "max_temperature_c": 45,
    "active_area_ft2": 440,
    "active_area_m2": 41,
    "nominal_flow_m3_day": 47.9,
    "nominal_flow_gpd": 12.65,
    "ph_range": "2-11",
    "length_inch": 40,
    "length_mm": 1016,
    "diameter_inch": 7.9,
    "diameter_mm": 200,
    "weight_kg": 16,
}

# Actual pilot vessel geometry clarified after the V100 run.
PILOT_VESSEL_COUNT = 1
PILOT_INSTALLED_ELEMENTS = 3
PILOT_VESSEL_CAPACITY_ELEMENTS = 4
PILOT_PRODUCT_M3H = 1.82
PILOT_TARGET_RECOVERY_PCT = 90.0
PILOT_FEED_M3H = PILOT_PRODUCT_M3H / (PILOT_TARGET_RECOVERY_PCT / 100.0)
PILOT_MIN_CONCENTRATE_FLOW_M3H = 4.54
PILOT_PF_DURATION_MIN = 1.24
PILOT_SYSTEM_VOLUME_M3 = 0.09
DEFAULT_WATER_PROFILE = "Well Water - Med Hardness"


def _active_area_m2(elements: int) -> float:
    return float(ACTUAL_MEMBRANE["active_area_m2"]) * float(elements)


def _flux_lmh(product_m3h: float, elements: int) -> float:
    area = _active_area_m2(elements)
    return product_m3h * 1000.0 / area if area > 0 else 0.0


def _base_plan(name: str, description: str, cases: list[dict[str, Any]], *, tier: str, wave_element: str) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "name": name,
        "plan_kit_version": PLAN_VERSION,
        "meeting_260709_campaign": True,
        "lg_bw440_pilot_campaign": True,
        "campaign_tier": tier,
        "description": description,
        "fresh_project_per_item": True,
        "defaults": {
            "allow_experimental_ro": True,
            "allow_experimental_batch": True,
            "fresh_project_per_item": True,
            "actual_membrane": ACTUAL_MEMBRANE,
            "wave_selected_element": wave_element,
            "pilot_geometry": {
                "vessel_count": PILOT_VESSEL_COUNT,
                "installed_elements_per_vessel": PILOT_INSTALLED_ELEMENTS,
                "vessel_capacity_elements": PILOT_VESSEL_CAPACITY_ELEMENTS,
                "installed_total_elements": PILOT_VESSEL_COUNT * PILOT_INSTALLED_ELEMENTS,
                "full_vessel_total_elements": PILOT_VESSEL_COUNT * PILOT_VESSEL_CAPACITY_ELEMENTS,
            },
            "notes": (
                "Generated by wave_lg_bw440_pilot_campaign.py.  Actual pilot is 1 pressure vessel "
                "with 3 installed LG BW 440 R G2 elements; vessel can physically hold 4 elements. "
                "If WAVE cannot select LG BW 440 R G2, use --wave-element with a WAVE catalog surrogate "
                "while keeping the LG membrane metadata for interpretation."
            ),
        },
        "cases": cases,
    }


def _ccro_case(
    case_id: str,
    *,
    wave_element: str,
    installed_elements: int = PILOT_INSTALLED_ELEMENTS,
    feed_flow_m3h: float = PILOT_FEED_M3H,
    recovery_pct: float = PILOT_TARGET_RECOVERY_PCT,
    pf_feed_ratio_pct: float | None = None,
    pf_recovery_pct: float = 10.0,
    water_profile: str = DEFAULT_WATER_PROFILE,
    feed_tds_mgL: float | None = None,
    tags: Iterable[str] = (),
    hypothesis: str = "",
    wave_manual_note: str = "",
) -> dict[str, Any]:
    product_flow = feed_flow_m3h * (recovery_pct / 100.0)
    tags_list = ["meeting_260709", "lg_bw440", "pilot_1vessel", f"{installed_elements}elements", "ccro", "hrro", *list(tags)]
    case: dict[str, Any] = {
        "id": case_id,
        "kind": "ccro_video",
        # WAVE selection string.  May be actual LG if available in catalog, or a surrogate passed by --wave-element.
        "ccro_element": wave_element,
        "ccro_water_profile": water_profile,
        "ccro_feed_flow": round(float(feed_flow_m3h), 6),
        "ccro_pass_count": 1,
        "ccro_recovery": round(float(recovery_pct), 6),
        "ccro_pdf_name": f"{case_id}.pdf",
        "calibration_tags": tags_list,
        # V101-compatible plan passthrough fields.  These are the important fix.
        "ccro_pv_per_stage": PILOT_VESSEL_COUNT,
        "ccro_elements_per_pv": int(installed_elements),
        "pv_per_stage": PILOT_VESSEL_COUNT,
        "elements_per_pv": int(installed_elements),
        "ccro_flow_factor": 0.85,
        "flow_factor": 0.85,
        "stage_flow_factor": 0.85,
        "ccro_pass_back_pressure_bar": 0.0,
        "pass_back_pressure_bar": 0.0,
        "stage_back_pressure_bar": 0.0,
        "actual_membrane": ACTUAL_MEMBRANE,
        "pilot_geometry": {
            "vessel_count": PILOT_VESSEL_COUNT,
            "installed_elements_per_vessel": int(installed_elements),
            "vessel_capacity_elements": PILOT_VESSEL_CAPACITY_ELEMENTS,
            "installed_total_elements": int(installed_elements) * PILOT_VESSEL_COUNT,
            "active_area_m2": round(_active_area_m2(installed_elements), 6),
            "design_product_flow_m3h": round(product_flow, 6),
            "design_flux_lmh_from_lg_area": round(_flux_lmh(product_flow, installed_elements), 6),
        },
        "meeting_260709": {
            "hypothesis": hypothesis,
            "wave_manual_note": wave_manual_note,
            "actual_membrane_model": "LG BW 440 R G2",
            "wave_selected_element": wave_element,
            "catalog_risk": (
                "If WAVE catalog does not contain LG BW 440 R G2, rerun generator with --wave-element "
                "using a WAVE-selectable 8-inch brackish 440 ft2 surrogate, then interpret results with LG area/spec metadata."
            ),
            "pilot_basis": {
                "product_flow_m3h": round(product_flow, 6),
                "feed_flow_m3h": round(feed_flow_m3h, 6),
                "target_recovery_pct": recovery_pct,
                "vessel_count": PILOT_VESSEL_COUNT,
                "installed_elements_per_vessel": int(installed_elements),
                "vessel_capacity_elements": PILOT_VESSEL_CAPACITY_ELEMENTS,
                "active_area_m2": round(_active_area_m2(installed_elements), 6),
                "estimated_flux_lmh_from_lg_area": round(_flux_lmh(product_flow, installed_elements), 6),
                "min_concentrate_flow_m3h": PILOT_MIN_CONCENTRATE_FLOW_M3H,
                "pf_duration_min": PILOT_PF_DURATION_MIN,
            },
            "verify_from_pdf": [
                "system.specific_energy_kwh_m3",
                "pass.feed_pressure_bar",
                "pass.average_flux_lmh",
                "ccro.pf_feed_ratio_pct",
                "ccro.pf_feed_flow_m3h_per_pv",
                "ccro.pf_sequence_duration_min",
                "design_warnings",
            ],
        },
    }
    if pf_feed_ratio_pct is not None:
        case["ccro_pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
        case["pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
        case["target_pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
        case["meeting_260709"]["target_pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
    case["ccro_pf_recovery_pct"] = float(pf_recovery_pct)
    case["pf_recovery_pct"] = float(pf_recovery_pct)
    case["meeting_260709"]["target_pf_recovery_pct"] = float(pf_recovery_pct)
    if feed_tds_mgL is not None:
        case["ccro_feed_tds_mgL"] = float(feed_tds_mgL)
        case["feed_tds_mgL"] = float(feed_tds_mgL)
        case["meeting_260709"]["target_feed_tds_mgL"] = float(feed_tds_mgL)
    return case


def _build_plans(wave_element: str) -> dict[str, dict[str, Any]]:
    plans: dict[str, dict[str, Any]] = {}

    # 1) Geometry baseline: current 3-element pilot vs full 4-element vessel.
    geometry_cases: list[dict[str, Any]] = []
    for elems in [3, 4]:
        for rec in [85.0, 90.0]:
            for fr in ([150.0, 270.0] if rec == 90.0 else [150.0]):
                geometry_cases.append(
                    _ccro_case(
                        f"V102_LG_BW440_{elems}E_R{int(rec)}_FR{int(fr)}",
                        wave_element=wave_element,
                        installed_elements=elems,
                        recovery_pct=rec,
                        pf_feed_ratio_pct=fr,
                        tags=["geometry_baseline", f"{elems}elements", f"r{int(rec)}", f"fr{int(fr)}"],
                        hypothesis=(
                            f"Actual pilot geometry test: 1 vessel x {elems} installed elements using LG BW 440 R G2 metadata. "
                            f"Compare R{rec:.0f}/FR{fr:.0f} pressure, flux, SEC, and WAVE warnings."
                        ),
                    )
                )
    plans["AquaNova_WAVE_V102_LG_BW440_01_geometry_baseline.json"] = _base_plan(
        "V102 LG BW440 01 - pilot geometry baseline",
        "Current 1 vessel x 3 installed elements and optional full 4-element vessel comparison.",
        geometry_cases,
        tier="lg_bw440_geometry_baseline",
        wave_element=wave_element,
    )

    # 2) PF Feed Ratio / pump-energy sweep for the corrected 1x3 pilot geometry.
    fr_cases: list[dict[str, Any]] = []
    for fr in [120.0, 150.0, 270.0, 300.0]:
        fr_cases.append(
            _ccro_case(
                f"V102_LG_BW440_3E_R90_FR{int(fr)}",
                wave_element=wave_element,
                installed_elements=3,
                recovery_pct=90.0,
                pf_feed_ratio_pct=fr,
                tags=["fr_sweep", "pump_energy", f"fr{int(fr)}"],
                hypothesis=(
                    f"Corrected pilot geometry 1V x 3E: compare PF Feed Ratio {fr:.0f}% against WAVE flow table, "
                    "specific energy, pressure, and warnings."
                ),
                wave_manual_note="If PF Feed Ratio is not automated, manually set it in WAVE before PDF export and verify via corpus.",
            )
        )
    plans["AquaNova_WAVE_V102_LG_BW440_02_fr_pump_energy_sweep.json"] = _base_plan(
        "V102 LG BW440 02 - FR / pump energy sweep",
        "FR120/150/270/300 on the corrected 1 vessel x 3 element pilot basis.",
        fr_cases,
        tier="lg_bw440_fr_pump_energy",
        wave_element=wave_element,
    )

    # 3) Product flow / flux push with 3 elements.
    flux_cases: list[dict[str, Any]] = []
    for product_flow in [1.60, 1.82, 2.10, 2.50, 3.00]:
        feed_flow = product_flow / 0.90
        flux_cases.append(
            _ccro_case(
                f"V102_LG_BW440_3E_FLUX_P{str(product_flow).replace('.', 'p')}_R90",
                wave_element=wave_element,
                installed_elements=3,
                feed_flow_m3h=feed_flow,
                recovery_pct=90.0,
                pf_feed_ratio_pct=270.0,
                tags=["flux_push", "same_membrane_count"],
                hypothesis=(
                    f"Same 1V x 3E pilot, product target about {product_flow:.2f} m3/h. "
                    "Check whether WAVE flags flux, element recovery, pressure, or SEC limits."
                ),
            )
        )
    plans["AquaNova_WAVE_V102_LG_BW440_03_product_flux_push_sweep.json"] = _base_plan(
        "V102 LG BW440 03 - product flow / flux push",
        "Increase product flow with the same 3 installed membranes to see WAVE warnings and pump/SEC impact.",
        flux_cases,
        tier="lg_bw440_flux_push",
        wave_element=wave_element,
    )

    # 4) Raw-water TDS / safety proxy; WAVE water editing may still require manual operation.
    tds_cases: list[dict[str, Any]] = []
    for tds in [450.0, 1000.0, 1500.0, 2000.0]:
        tds_cases.append(
            _ccro_case(
                f"V102_LG_BW440_3E_TDS{int(tds):04d}_R90",
                wave_element=wave_element,
                installed_elements=3,
                recovery_pct=90.0,
                pf_feed_ratio_pct=270.0,
                feed_tds_mgL=tds,
                tags=["raw_tds_safety", "adaptive_recovery", "conductivity_limit"],
                hypothesis=(
                    f"Feed TDS target {tds:.0f} mg/L on 1V x 3E pilot.  Check whether WAVE pressure/TDS/warnings support "
                    "early PF transition / lower actual recovery rather than forcing R90 at unsafe pressure."
                ),
                wave_manual_note=(
                    "If water-profile TDS is not automated, manually edit feed water to this TDS before export. "
                    "The case id and metadata keep the target TDS for post-analysis."
                ),
            )
        )
    plans["AquaNova_WAVE_V102_LG_BW440_04_raw_tds_safety_sweep.json"] = _base_plan(
        "V102 LG BW440 04 - raw TDS / adaptive safety sweep",
        "TDS 450/1000/1500/2000 labels for conductivity-limit and early-PF discussion.",
        tds_cases,
        tier="lg_bw440_raw_tds_safety",
        wave_element=wave_element,
    )

    return plans


def _handcalc_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for elems in [3, 4]:
        for fr in [120.0, 150.0, 270.0, 300.0]:
            q_pf_feed = PILOT_PRODUCT_M3H * fr / 100.0
            q_drain = max(0.0, q_pf_feed - PILOT_PRODUCT_M3H)
            q_membrane_total_feed = PILOT_PRODUCT_M3H + PILOT_MIN_CONCENTRATE_FLOW_M3H
            q_assist_or_recycle = max(0.0, q_membrane_total_feed - q_pf_feed)
            ideal_assist_l = q_assist_or_recycle * 1000.0 * (PILOT_PF_DURATION_MIN / 60.0)
            rows.append(
                {
                    "installed_elements": elems,
                    "vessel_capacity_elements": PILOT_VESSEL_CAPACITY_ELEMENTS,
                    "active_area_m2": round(_active_area_m2(elems), 6),
                    "product_flow_m3h": PILOT_PRODUCT_M3H,
                    "estimated_flux_lmh": round(_flux_lmh(PILOT_PRODUCT_M3H, elems), 6),
                    "pf_feed_ratio_pct": fr,
                    "q_pf_feed_m3h": round(q_pf_feed, 6),
                    "q_drain_setpoint_m3h": round(q_drain, 6),
                    "q_membrane_total_feed_m3h": round(q_membrane_total_feed, 6),
                    "q_min_concentrate_flow_m3h": round(PILOT_MIN_CONCENTRATE_FLOW_M3H, 6),
                    "q_p3_or_bladder_assist_required_m3h": round(q_assist_or_recycle, 6),
                    "pf_duration_min": PILOT_PF_DURATION_MIN,
                    "ideal_assist_volume_liters": round(ideal_assist_l, 3),
                    "assist_volume_liters_margin_x2_5": round(ideal_assist_l * 2.5, 3),
                    "note": "Ideal hydraulic assist only; add actual pipe/vessel volume, bladder drawdown, valve Cv, and safety margin.",
                }
            )
    return rows


def _write_handcalc(output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    rows = _handcalc_rows()
    csv_path = output_dir / "wave_260709_lg_bw440_pilot_handcalc.csv"
    md_path = output_dir / "wave_260709_lg_bw440_pilot_handcalc.md"
    with csv_path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    lines = [
        "# 2026-07-09 LG BW 440 R G2 pilot hand calculation",
        "",
        "Actual pilot clarification: 1 pressure vessel, 3 installed elements, vessel can physically hold 4 elements.",
        "",
        "Membrane: LG BW 440 R G2, active area 440 ft2 / 41 m2 per element, average NaCl rejection 99.78%, max pressure 41.4 bar.",
        "",
        "| Elements | Area m2 | Product m3/h | Flux LMH | FR % | PF feed m3/h | drain m3/h | assist/recycle m3/h | ideal assist L | x2.5 margin L |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(
            f"| {r['installed_elements']} | {r['active_area_m2']:.1f} | {r['product_flow_m3h']:.2f} | "
            f"{r['estimated_flux_lmh']:.2f} | {r['pf_feed_ratio_pct']:.0f} | {r['q_pf_feed_m3h']:.3f} | "
            f"{r['q_drain_setpoint_m3h']:.3f} | {r['q_p3_or_bladder_assist_required_m3h']:.3f} | "
            f"{r['ideal_assist_volume_liters']:.1f} | {r['assist_volume_liters_margin_x2_5']:.1f} |"
        )
    lines.extend([
        "",
        "Interpretation:",
        "- 3 installed elements give about 123 m2 active area; 1.82 m3/h product is about 14.8 LMH.",
        "- A full 4-element vessel would give about 164 m2 active area; 1.82 m3/h product is about 11.1 LMH.",
        "- WAVE cannot directly model bladder/accumulator transient assist, so compare WAVE PF flow table with this hand calculation.",
        "- If WAVE cannot select LG BW 440 R G2, use a WAVE catalog surrogate and interpret with this LG-area hand calculation.",
        "",
    ])
    md_path.write_text("\n".join(lines), encoding="utf-8")
    return csv_path, md_path


def write_plans(wave_records_dir: Path, plans: dict[str, dict[str, Any]]) -> list[Path]:
    wave_records_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for filename, plan in plans.items():
        path = wave_records_dir / filename
        path.write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def summary(plans: dict[str, dict[str, Any]]) -> dict[str, Any]:
    kind_counts: dict[str, int] = {}
    tag_counts: dict[str, int] = {}
    element_counts: dict[str, int] = {}
    for plan in plans.values():
        for case in plan.get("cases", []):
            kind = str(case.get("kind", "unknown"))
            kind_counts[kind] = kind_counts.get(kind, 0) + 1
            elems = str(case.get("elements_per_pv", "unknown"))
            element_counts[elems] = element_counts.get(elems, 0) + 1
            for tag in case.get("calibration_tags", []):
                tag_counts[str(tag)] = tag_counts.get(str(tag), 0) + 1
    return {
        "schema_version": f"aquanova.wave_meeting_260709.{PLAN_VERSION}",
        "plan_count": len(plans),
        "case_count": sum(len(plan.get("cases", [])) for plan in plans.values()),
        "kind_counts": kind_counts,
        "element_counts": element_counts,
        "tag_counts": tag_counts,
    }


def _demo_command(path: Path, *, current_dir: Path) -> str:
    scripts_dir = Path(__file__).resolve().parent
    if current_dir.resolve() == scripts_dir.resolve():
        demo = r".\wave_records\wave_video_demo.py"
    else:
        demo = r".\scripts\wave_records\wave_video_demo.py"
    return (
        f"python {demo} `\n"
        f"  --run-production-plan \"{path}\" `\n"
        "  --production-max-attempts 2 `\n"
        "  --production-restart-monitor-index 2 `\n"
        "  --production-rerun-completed `\n"
        "  --allow-experimental-ro `\n"
        "  --allow-experimental-batch"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate WAVE pilot plans for LG BW 440 R G2 / 1V x 3E clarification.")
    parser.add_argument("--write", action="store_true", help="Write plan JSON files and handcalc files.")
    parser.add_argument("--wave-element", default="LG BW 440 R G2", help="Element name to select in WAVE catalog. Default: actual LG model name.")
    parser.add_argument("--output-dir", default=None, help="Plan output directory. Default: <scripts>/wave_records")
    parser.add_argument("--handcalc-dir", default=None, help="Handcalc output directory. Default: <scripts>/wave_records/results/_meeting_260709_lg_bw440")
    parser.add_argument("--print-summary", action="store_true")
    parser.add_argument("--print-run-commands", action="store_true")
    parser.add_argument("--first-only", action="store_true", help="Print only the first/safest run command.")
    args = parser.parse_args()

    scripts_dir = Path(__file__).resolve().parent
    wave_records_dir = Path(args.output_dir).resolve() if args.output_dir else scripts_dir / "wave_records"
    handcalc_dir = Path(args.handcalc_dir).resolve() if args.handcalc_dir else wave_records_dir / "results" / "_meeting_260709_lg_bw440"
    plans = _build_plans(args.wave_element)

    if args.write:
        paths = write_plans(wave_records_dir, plans)
        csv_path, md_path = _write_handcalc(handcalc_dir)
        print(f"V102 LG BW440 pilot WAVE campaign written: {len(paths)} plan file(s)")
        print(f"wave_selected_element={args.wave_element}")
        for path in paths:
            print(path)
        print(f"handcalc_csv: {csv_path}")
        print(f"handcalc_markdown: {md_path}")
    else:
        paths = [wave_records_dir / filename for filename in plans]

    if args.print_summary:
        print("summary=" + json.dumps(summary(plans), ensure_ascii=False, sort_keys=True))

    if args.print_run_commands:
        print("\nRun commands:")
        selected_paths = paths[:1] if args.first_only else paths
        for path in selected_paths:
            print("\n" + _demo_command(path, current_dir=Path.cwd()))

    if not args.write and not args.print_summary and not args.print_run_commands:
        parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
