#!/usr/bin/env python3
r"""Generate WAVE test plans for the 2026-07-09 HRRO/CCRO meeting.

Run from the AquaNova scripts directory:

    cd C:\Users\a\Desktop\프로젝트\AquaNova\code\scripts
    python .\wave_260709_meeting_campaign.py --write --print-summary --print-run-commands

This script writes WAVE production-plan JSON files under ./wave_records and a
small meeting-handcalc CSV/Markdown under ./wave_records/results/_meeting_260709.

The plans focus on the meeting questions:
  1) PF Feed Ratio / pump-energy comparison: 120, 150, 270, 300%.
  2) Product-flow / flux push: can the existing membrane count produce more
     permeate, and what WAVE warnings appear?
  3) Feed-water TDS/adaptive-safety proxies: 450, 1000, 1500, 2000 mg/L labels.
  4) Two-pass high-recovery stress cases.
  5) Bladder/pressure-tank PF assist hand calculation.

Compatibility note:
Existing wave_video_demo.py versions may not automate every WAVE field shown in
this script, especially PF Feed Ratio and custom feed TDS.  The JSON includes
both standard fields and explicit meeting metadata.  After running WAVE, use
wave_260709_meeting_analyze.py to confirm from the PDF corpus what WAVE actually
used, especially ccro.pf_feed_ratio_pct and design_warnings.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

SCHEMA_VERSION = 1
PLAN_VERSION = "V100_260709"
DEFAULT_ELEMENT = "FilmTec™ SOAR 5000i"
DEFAULT_WATER_PROFILE = "Well Water - Med Hardness"
DEFAULT_UF_MODULE = "Ultrafiltration SFP-2660"

# Pilot basis discussed in the meeting / previous WAVE PDF.
PILOT_PRODUCT_M3H = 1.82
PILOT_TARGET_RECOVERY_PCT = 90.0
PILOT_FEED_M3H = PILOT_PRODUCT_M3H / (PILOT_TARGET_RECOVERY_PCT / 100.0)
PILOT_PV_PER_STAGE = 1
PILOT_ELEMENTS_PER_PV = 3
PILOT_MIN_CONCENTRATE_FLOW_M3H = 4.54
PILOT_PF_DURATION_MIN = 1.24
PILOT_SYSTEM_VOLUME_M3 = 0.09


@dataclass(frozen=True)
class MeetingCase:
    id: str
    kind: str
    case: dict[str, Any]


def _project_root_from_scripts_dir(scripts_dir: Path) -> Path:
    scripts_dir = scripts_dir.resolve()
    if scripts_dir.name.lower() == "scripts":
        return scripts_dir.parent
    # Allow accidental run from project root; then __file__ may still be scripts/...
    if (scripts_dir / "scripts").exists():
        return scripts_dir
    return scripts_dir.parent


def _base_plan(name: str, description: str, cases: list[dict[str, Any]], *, tier: str) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "name": name,
        "plan_kit_version": PLAN_VERSION,
        "meeting_260709_campaign": True,
        "campaign_tier": tier,
        "description": description,
        "fresh_project_per_item": True,
        "defaults": {
            "allow_experimental_ro": True,
            "allow_experimental_batch": True,
            "fresh_project_per_item": True,
            "meeting_260709_campaign": True,
            "notes": (
                "Generated by wave_260709_meeting_campaign.py.  These are WAVE "
                "test anchors for pump energy, PF Feed Ratio, flux, raw-water "
                "safety, and bladder-tank PF-assist discussion from the 2026-07-09 meeting."
            ),
        },
        "cases": cases,
    }


def _ccro_case(
    case_id: str,
    *,
    feed_flow_m3h: float = PILOT_FEED_M3H,
    recovery_pct: float = PILOT_TARGET_RECOVERY_PCT,
    pass_count: int = 1,
    pass2_recovery_pct: float | None = None,
    pf_feed_ratio_pct: float | None = None,
    pf_recovery_pct: float | None = 10.0,
    water_profile: str = DEFAULT_WATER_PROFILE,
    feed_tds_mgL: float | None = None,
    tags: Iterable[str] = (),
    hypothesis: str = "",
    wave_manual_note: str = "",
) -> dict[str, Any]:
    """Build a CCRO video case with extra fields for meeting traceability.

    Standard fields match the V84/V86 production-plan style.  Extra fields are
    kept under meeting_260709 and are safe metadata even if wave_video_demo.py
    does not yet consume them.
    """
    tags_list = ["meeting_260709", "ccro", "hrro", *list(tags)]
    case: dict[str, Any] = {
        "id": case_id,
        "kind": "ccro_video",
        "ccro_element": DEFAULT_ELEMENT,
        "ccro_water_profile": water_profile,
        "ccro_feed_flow": round(float(feed_flow_m3h), 6),
        "ccro_pass_count": int(pass_count),
        "ccro_recovery": round(float(recovery_pct), 6),
        "ccro_pdf_name": f"{case_id}.pdf",
        "calibration_tags": tags_list,
        # Compatibility hints for newer automation variants.
        "ccro_pv_per_stage": PILOT_PV_PER_STAGE,
        "ccro_elements_per_pv": PILOT_ELEMENTS_PER_PV,
        "pv_per_stage": PILOT_PV_PER_STAGE,
        "elements_per_pv": PILOT_ELEMENTS_PER_PV,
        "ccro_flow_factor": 0.85,
        "ccro_pass_back_pressure_bar": 0.0,
        "meeting_260709": {
            "hypothesis": hypothesis,
            "wave_manual_note": wave_manual_note,
            "pilot_basis": {
                "product_flow_m3h": PILOT_PRODUCT_M3H,
                "feed_flow_m3h": round(PILOT_FEED_M3H, 6),
                "target_recovery_pct": PILOT_TARGET_RECOVERY_PCT,
                "pv_per_stage": PILOT_PV_PER_STAGE,
                "elements_per_pv": PILOT_ELEMENTS_PER_PV,
                "min_concentrate_flow_m3h": PILOT_MIN_CONCENTRATE_FLOW_M3H,
                "pf_duration_min": PILOT_PF_DURATION_MIN,
            },
            "verify_from_pdf": [
                "system.specific_energy_kwh_m3",
                "pass.feed_pressure_bar",
                "pass.average_flux_lmh",
                "ccro.pf_feed_ratio_pct",
                "ccro.pf_feed_flow_m3h_per_pv",
                "ccro.pf_sequence_duration_min",
                "design_warnings",
            ],
        },
    }
    if pass_count >= 2:
        case["ccro_pass2_recovery"] = float(pass2_recovery_pct if pass2_recovery_pct is not None else recovery_pct)
        case["ccro_pass2_pv_per_stage"] = 1
        case["ccro_pass2_elements_per_pv"] = 3
        case["pass2_pv_per_stage"] = 1
        case["pass2_elements_per_pv"] = 3
    if pf_feed_ratio_pct is not None:
        # These fields are intentionally redundant.  Older automation may ignore
        # them; future automation can consume one of them without changing this script.
        case["ccro_pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
        case["pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
        case["target_pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
        case["meeting_260709"]["target_pf_feed_ratio_pct"] = float(pf_feed_ratio_pct)
    if pf_recovery_pct is not None:
        case["ccro_pf_recovery_pct"] = float(pf_recovery_pct)
        case["pf_recovery_pct"] = float(pf_recovery_pct)
        case["meeting_260709"]["target_pf_recovery_pct"] = float(pf_recovery_pct)
    if feed_tds_mgL is not None:
        case["ccro_feed_tds_mgL"] = float(feed_tds_mgL)
        case["feed_tds_mgL"] = float(feed_tds_mgL)
        case["meeting_260709"]["target_feed_tds_mgL"] = float(feed_tds_mgL)
    return case


def _build_plans() -> dict[str, dict[str, Any]]:
    plans: dict[str, dict[str, Any]] = {}

    # 1) Direct meeting question: PF Feed Ratio / pump energy / WAVE warning.
    fr_cases: list[dict[str, Any]] = []
    for fr in [120.0, 150.0, 270.0, 300.0]:
        fr_cases.append(
            _ccro_case(
                f"V100_MTG_260709_FR{int(fr):03d}_PILOT_R90",
                pf_feed_ratio_pct=fr,
                tags=["fr_sweep", f"fr_{int(fr)}", "pump_energy"],
                hypothesis=(
                    "Compare WAVE flow table, pump/boost pressure, SEC, and warnings at "
                    f"PF Feed Ratio {fr:.0f}%.  Meeting question: is FR270/300 only needed "
                    "because WAVE true-plug-flow requires high PF flow, and does FR150 trigger "
                    "a PF Feed Ratio / concentrate-flow warning?"
                ),
                wave_manual_note=(
                    "If this wave_video_demo build does not automate PF Feed Ratio, open WAVE "
                    f"CCRO Flow Calculator / PF settings manually and set PF Feed Ratio={fr:.0f}% "
                    "before exporting the PDF.  The analyzer will still report the actual PDF ratio."
                ),
            )
        )
    plans["AquaNova_WAVE_V100_260709_01_fr_pump_energy_sweep.json"] = _base_plan(
        "V100 260709 01 - PF Feed Ratio / pump-energy sweep",
        "Pilot CCRO cases for FR120/150/270/300.  Use PDF flow table and SEC to decide whether pump downsizing or WAVE FR settings explain the energy gap.",
        fr_cases,
        tier="meeting_fr_pump_energy",
    )

    # 2) Product-flow / flux push: the meeting explicitly asked what WAVE error appears
    # when trying to increase permeate production with the same membranes.
    flux_cases: list[dict[str, Any]] = []
    for product_flow in [1.60, 1.82, 2.10, 2.50, 3.00]:
        feed_flow = product_flow / 0.90
        flux_cases.append(
            _ccro_case(
                f"V100_MTG_260709_FLUX_P{str(product_flow).replace('.', 'p')}_R90",
                feed_flow_m3h=feed_flow,
                recovery_pct=90.0,
                pf_feed_ratio_pct=270.0,
                tags=["flux_push", "same_membrane_count", "pump_utilization"],
                hypothesis=(
                    f"Try product flow about {product_flow:.2f} m3/h with the same 1PV x 3 element pilot. "
                    "Meeting question: if feed/product flow is increased to use the pump harder, does WAVE raise "
                    "permeate flux or element recovery warnings?"
                ),
                wave_manual_note="Check average flux, stage/element recovery warning, and specific energy in the exported PDF.",
            )
        )
    plans["AquaNova_WAVE_V100_260709_02_product_flux_push_sweep.json"] = _base_plan(
        "V100 260709 02 - product-flow / flux push sweep",
        "Same membrane count, higher product-flow targets.  This answers whether increasing throughput is blocked by flux / element recovery warnings.",
        flux_cases,
        tier="meeting_flux_push",
    )

    # 3) Feed TDS/adaptive safety.  WAVE automation may need manual water edit,
    # but names/targets are encoded so exported PDFs and corpus rows can be reviewed.
    tds_cases: list[dict[str, Any]] = []
    for tds in [450.0, 1000.0, 1500.0, 2000.0]:
        tds_cases.append(
            _ccro_case(
                f"V100_MTG_260709_TDS{int(tds):04d}_R90",
                recovery_pct=90.0,
                pf_feed_ratio_pct=270.0,
                feed_tds_mgL=tds,
                tags=["raw_tds_safety", "adaptive_recovery", "conductivity_limit"],
                hypothesis=(
                    f"Feed TDS target {tds:.0f} mg/L at nominal R90.  Meeting question: when raw water rises "
                    "from clean 450 mg/L toward 1000-2000 mg/L, does WAVE pressure/TDS/warning behavior imply "
                    "conductivity-limit PF transition rather than forcing R90 with pressure?"
                ),
                wave_manual_note=(
                    "Existing automation may only select a water library profile.  If custom feed TDS is not automated, "
                    f"manually edit/feed-water profile to about {tds:.0f} mg/L before export."
                ),
            )
        )
    plans["AquaNova_WAVE_V100_260709_03_raw_tds_safety_sweep.json"] = _base_plan(
        "V100 260709 03 - raw TDS / adaptive-safety sweep",
        "TDS labels for conductivity-limit / early-PF-transition discussion.  Manual WAVE water edits may be required depending on automation support.",
        tds_cases,
        tier="meeting_raw_tds_safety",
    )

    # 4) Two-pass/high-recovery stress: relevant for pressure and recovery protection logic.
    stress_cases = [
        _ccro_case(
            "V100_MTG_260709_2PASS_P1R90_P2R90",
            pass_count=2,
            recovery_pct=90.0,
            pass2_recovery_pct=90.0,
            pf_feed_ratio_pct=270.0,
            tags=["two_pass", "stress", "adaptive_recovery"],
            hypothesis="Two-pass R90/R90 pressure, flux, TDS, and SEC baseline for adaptive recovery discussion.",
        ),
        _ccro_case(
            "V100_MTG_260709_2PASS_P1R90_P2R95",
            pass_count=2,
            recovery_pct=90.0,
            pass2_recovery_pct=95.0,
            pf_feed_ratio_pct=270.0,
            tags=["two_pass", "stress", "high_recovery"],
            hypothesis="Two-pass stress with pass 2 high recovery.  Check whether WAVE warnings support lower actual recovery / PF transition logic.",
        ),
        _ccro_case(
            "V100_MTG_260709_1PASS_R95_FR270",
            pass_count=1,
            recovery_pct=95.0,
            pf_feed_ratio_pct=270.0,
            tags=["one_pass", "stress", "high_recovery"],
            hypothesis="One-pass R95 stress case.  Check WAVE warnings and pressure/SEC against R90 baseline.",
        ),
    ]
    plans["AquaNova_WAVE_V100_260709_04_high_recovery_stress.json"] = _base_plan(
        "V100 260709 04 - high-recovery/two-pass stress",
        "Stress cases for recovery protection / early PF / CIP discussion.",
        stress_cases,
        tier="meeting_high_recovery_stress",
    )

    return plans


def _bladder_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for fr in [120.0, 150.0, 270.0, 300.0]:
        q_pf_feed = PILOT_PRODUCT_M3H * fr / 100.0
        q_drain = max(0.0, q_pf_feed - PILOT_PRODUCT_M3H)
        q_membrane_total_feed = PILOT_PRODUCT_M3H + PILOT_MIN_CONCENTRATE_FLOW_M3H
        q_p3_recycle = max(0.0, q_membrane_total_feed - q_pf_feed)
        q_tank_makeup = max(0.0, PILOT_MIN_CONCENTRATE_FLOW_M3H - q_drain)
        volume_l = q_tank_makeup * 1000.0 * (PILOT_PF_DURATION_MIN / 60.0)
        rows.append(
            {
                "case": f"FR{int(fr)}",
                "product_flow_m3h": round(PILOT_PRODUCT_M3H, 6),
                "pf_feed_ratio_pct": fr,
                "q_pf_feed_m3h": round(q_pf_feed, 6),
                "q_drain_setpoint_m3h": round(q_drain, 6),
                "q_membrane_total_feed_m3h": round(q_membrane_total_feed, 6),
                "q_min_concentrate_flow_m3h": round(PILOT_MIN_CONCENTRATE_FLOW_M3H, 6),
                "q_p3_recycle_required_m3h": round(q_p3_recycle, 6),
                "q_bladder_or_accumulator_makeup_m3h": round(q_tank_makeup, 6),
                "pf_duration_min": PILOT_PF_DURATION_MIN,
                "ideal_makeup_volume_liters": round(volume_l, 3),
                "note": "Ideal hydraulic makeup only; add vessel/pipe volume and bladder drawdown margin before hardware sizing.",
            }
        )
    return rows


def _write_handcalc(output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    rows = _bladder_rows()
    csv_path = output_dir / "wave_260709_bladder_pf_assist_handcalc.csv"
    md_path = output_dir / "wave_260709_bladder_pf_assist_handcalc.md"
    with csv_path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    lines = [
        "# 2026-07-09 bladder / accumulator PF-assist hand calculation",
        "",
        "This is not a direct WAVE model.  It converts the meeting hypothesis into quantities that should be compared with WAVE PF flow-table outputs.",
        "",
        "| Case | PF Feed Ratio % | PF feed m3/h | drain setpoint m3/h | P-3 recycle required m3/h | accumulator makeup m3/h | ideal makeup L |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            f"| {row['case']} | {row['pf_feed_ratio_pct']:.0f} | {row['q_pf_feed_m3h']:.3f} | "
            f"{row['q_drain_setpoint_m3h']:.3f} | {row['q_p3_recycle_required_m3h']:.3f} | "
            f"{row['q_bladder_or_accumulator_makeup_m3h']:.3f} | {row['ideal_makeup_volume_liters']:.1f} |"
        )
    lines.extend(
        [
            "",
            "Interpretation:",
            "- FR150 gives about 2.73 m3/h PF feed and 0.91 m3/h external drain on a 1.82 m3/h product basis.",
            "- The remaining membrane crossflow must come from P-3 recycle and/or a PF assist source.",
            "- WAVE cannot directly represent a bladder/accumulator transient, so use this table as a sizing/check note next to the WAVE PDF flow table.",
            "",
        ]
    )
    md_path.write_text("\n".join(lines), encoding="utf-8")
    return csv_path, md_path


def write_plans(wave_records_dir: Path, plans: dict[str, dict[str, Any]]) -> list[Path]:
    wave_records_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for filename, plan in plans.items():
        path = wave_records_dir / filename
        path.write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def summary(plans: dict[str, dict[str, Any]]) -> dict[str, Any]:
    kind_counts: dict[str, int] = {}
    tag_counts: dict[str, int] = {}
    for plan in plans.values():
        for case in plan.get("cases", []):
            kind = str(case.get("kind", "unknown"))
            kind_counts[kind] = kind_counts.get(kind, 0) + 1
            for tag in case.get("calibration_tags", []):
                tag_counts[str(tag)] = tag_counts.get(str(tag), 0) + 1
    return {
        "schema_version": f"aquanova.wave_meeting_260709.{PLAN_VERSION}",
        "plan_count": len(plans),
        "case_count": sum(len(plan.get("cases", [])) for plan in plans.values()),
        "kind_counts": kind_counts,
        "tag_counts": tag_counts,
    }


def _demo_command(path: Path, *, current_dir: Path) -> str:
    current_dir = current_dir.resolve()
    scripts_dir = Path(__file__).resolve().parent
    # If user runs from code\scripts, wave_video_demo is .\wave_records\wave_video_demo.py.
    if current_dir == scripts_dir.resolve():
        demo = r".\wave_records\wave_video_demo.py"
    else:
        demo = r".\scripts\wave_records\wave_video_demo.py"
    return (
        f"python {demo} `\n"
        f"  --run-production-plan \"{path}\" `\n"
        "  --production-max-attempts 2 `\n"
        "  --production-restart-monitor-index 2 `\n"
        "  --production-rerun-completed `\n"
        "  --allow-experimental-ro `\n"
        "  --allow-experimental-batch"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate WAVE test plans for the 2026-07-09 meeting.")
    parser.add_argument("--write", action="store_true", help="Write plan JSON files and bladder handcalc files.")
    parser.add_argument("--output-dir", default=None, help="Plan output directory. Default: <scripts>/wave_records")
    parser.add_argument("--handcalc-dir", default=None, help="Handcalc output directory. Default: <scripts>/wave_records/results/_meeting_260709")
    parser.add_argument("--print-summary", action="store_true")
    parser.add_argument("--print-run-commands", action="store_true")
    parser.add_argument("--first-only", action="store_true", help="Print only the first/safest run command.")
    args = parser.parse_args()

    scripts_dir = Path(__file__).resolve().parent
    wave_records_dir = Path(args.output_dir).resolve() if args.output_dir else scripts_dir / "wave_records"
    handcalc_dir = Path(args.handcalc_dir).resolve() if args.handcalc_dir else wave_records_dir / "results" / "_meeting_260709"
    plans = _build_plans()

    if args.write:
        paths = write_plans(wave_records_dir, plans)
        csv_path, md_path = _write_handcalc(handcalc_dir)
        print(f"V100 2026-07-09 WAVE meeting campaign written: {len(paths)} plan file(s)")
        for path in paths:
            print(path)
        print(f"handcalc_csv: {csv_path}")
        print(f"handcalc_markdown: {md_path}")
    else:
        paths = [wave_records_dir / filename for filename in plans]

    if args.print_summary:
        print("summary=" + json.dumps(summary(plans), ensure_ascii=False, sort_keys=True))

    if args.print_run_commands:
        print("\nRun commands:")
        selected_paths = paths[:1] if args.first_only else paths
        for path in selected_paths:
            print("\n" + _demo_command(path, current_dir=Path.cwd()))

    if not args.write and not args.print_summary and not args.print_run_commands:
        parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
