#!/usr/bin/env python3
r"""Generate V84 WAVE anchor-extraction campaign plans.

V84 changes the workflow from ad-hoc WAVE report generation to a deliberate
calibration campaign.  The plans created here are not intended to be one giant
10,000-case GUI run.  They are small restart-safe WAVE anchor batches that can
be used to train/validate nonlinear AquaNova correction layers.

Run from the AquaNova project root after applying the patch:

    python .\scripts\wave_records\wave_v84_calibration_campaign_export.py --print-summary

Then execute individual JSON plans with wave_video_demo.py using
--production-restart-monitor-index 2 and --production-rerun-completed when you
want to regenerate anchors.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence
import sys

SCHEMA_VERSION = 1
PLAN_KIT_VERSION = "V84"
EXCEL_MATRIX = "AquaNova_WAVE_RO_NF_Experimental_Test_Matrix_V46_2026-07-03.xlsx"
DEFAULT_RO_SHEET = "09_NF_BASELINE"
DEFAULT_WATER_PROFILE = "Well Water - Med Hardness"
DEFAULT_UF_MODULE = "Ultrafiltration SFP-2660"
DEFAULT_CCRO_ELEMENT = "FilmTec™ SOAR 5000i"


@dataclass(frozen=True)
class CampaignPlan:
    filename: str
    name: str
    description: str
    cases: list[dict[str, Any]]
    tier: str = "anchor"


def _defaults(*, tier: str, ro_sheet: str) -> dict[str, Any]:
    return {
        "allow_experimental_ro": True,
        "allow_experimental_batch": True,
        "fresh_project_per_item": True,
        "ro_sheet": ro_sheet,
        "campaign_tier": tier,
        "notes": (
            "Generated by V84 calibration campaign exporter.  These are WAVE "
            "anchor runs for nonlinear AquaNova calibration, not the full 10k "
            "AquaNova grid.  Each item is isolated with a fresh WAVE project."
        ),
    }


def _plan(name: str, description: str, cases: list[dict[str, Any]], *, tier: str, ro_sheet: str) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "name": name,
        "plan_kit_version": PLAN_KIT_VERSION,
        "calibration_campaign": True,
        "campaign_tier": tier,
        "description": description,
        "fresh_project_per_item": True,
        "defaults": _defaults(tier=tier, ro_sheet=ro_sheet),
        "cases": cases,
    }


def _ro_order_range(
    case_id: str,
    start: int,
    end: int,
    *,
    sheet: str,
    expected_case_count: int | None = None,
) -> dict[str, Any]:
    expected = int(expected_case_count if expected_case_count is not None else (int(end) - int(start) + 1))
    return {
        "id": case_id,
        "kind": "ro_excel",
        "path": EXCEL_MATRIX,
        "sheet": sheet,
        "start_order": int(start),
        "end_order": int(end),
        "expected_case_count": max(0, expected),
        "allow_experimental_ro": True,
        "calibration_tags": ["ro_nf", "excel_matrix", "wave_anchor"],
    }


def _uf_case(case_id: str, *, flow: float, module: str = DEFAULT_UF_MODULE) -> dict[str, Any]:
    return {
        "id": case_id,
        "kind": "uf_video",
        "uf_module": module,
        "uf_water_profile": DEFAULT_WATER_PROFILE,
        "uf_feed_flow": float(flow),
        "uf_pdf_name": f"{case_id}.pdf",
        "calibration_tags": ["uf", "flow_sweep", "wave_anchor"],
    }


def _ccro_case(
    case_id: str,
    *,
    flow: float = 100.0,
    pass_count: int = 1,
    recovery: float = 90.0,
    pass2_recovery: float | None = None,
    tags: Iterable[str] = (),
) -> dict[str, Any]:
    case: dict[str, Any] = {
        "id": case_id,
        "kind": "ccro_video",
        "ccro_element": DEFAULT_CCRO_ELEMENT,
        "ccro_water_profile": DEFAULT_WATER_PROFILE,
        "ccro_feed_flow": float(flow),
        "ccro_pass_count": int(pass_count),
        "ccro_recovery": float(recovery),
        "ccro_pdf_name": f"{case_id}.pdf",
        "calibration_tags": ["ccro", "hrro", "wave_anchor", *list(tags)],
    }
    if int(pass_count) >= 2:
        case["ccro_pass2_recovery"] = float(pass2_recovery if pass2_recovery is not None else recovery)
    return case


def _chunk_ranges(start: int, end: int, chunk_size: int) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    cur = int(start)
    while cur <= int(end):
        nxt = min(int(end), cur + int(chunk_size) - 1)
        ranges.append((cur, nxt))
        cur = nxt + 1
    return ranges


def _non_empty_order_chunks(
    available_orders: Sequence[int],
    *,
    start: int,
    end: int,
    chunk_size: int,
) -> list[tuple[int, int, int]]:
    """Return order ranges that actually contain runnable RO/NF cases.

    V84 originally wrote fixed 001-010, 011-020 ... ranges without checking the
    Excel sheet.  On the user's matrix the first sheet only contained three
    runnable cases, so the 011-020 plan failed before WAVE even clicked.  This
    helper keeps only non-empty buckets and records the expected case count for
    accurate summaries and run-command output.
    """
    start = int(start)
    end = int(end)
    chunk_size = max(1, int(chunk_size))
    filtered = sorted({int(order) for order in available_orders if start <= int(order) <= end})
    buckets: dict[int, list[int]] = {}
    for order in filtered:
        bucket_index = (order - start) // chunk_size
        buckets.setdefault(bucket_index, []).append(order)
    ranges: list[tuple[int, int, int]] = []
    for bucket_index in sorted(buckets):
        orders = buckets[bucket_index]
        ranges.append((min(orders), max(orders), len(orders)))
    return ranges


def _try_load_ro_case_orders(excel_path: Path, sheet: str) -> list[int] | None:
    """Load runnable RO/NF batch orders when the Excel matrix is available.

    Returns None when preflight is impossible, and an empty list when preflight
    succeeded but the sheet has no runnable rows.
    """
    if not excel_path.exists():
        return None
    try:
        from wave_ro_excel import load_ro_cases

        cases = load_ro_cases(excel_path, sheet)
        return [int(case.batch_order) for case in cases]
    except Exception as exc:  # pragma: no cover - defensive runtime diagnostic
        print(
            f"warning: RO/NF preflight failed for {excel_path.name}:{sheet}: {exc}",
            file=sys.stderr,
        )
        return None


def build_campaign_plans(
    *,
    ro_sheet: str = DEFAULT_RO_SHEET,
    ro_start_order: int = 1,
    ro_end_order: int = 45,
    ro_chunk_size: int = 10,
    available_ro_orders: Sequence[int] | None = None,
) -> dict[str, dict[str, Any]]:
    """Return restart-safe WAVE anchor campaign plans.

    The WAVE GUI should be used for hundreds of high-quality anchor PDFs, not
    for the full nonlinear training grid.  The large 10k+ grid should be run by
    AquaNova internally after these anchor plans establish WAVE targets.
    """
    plans: dict[str, dict[str, Any]] = {}

    if available_ro_orders is None:
        ro_ranges = [
            (start, end, end - start + 1)
            for start, end in _chunk_ranges(ro_start_order, ro_end_order, ro_chunk_size)
        ]
    else:
        ro_ranges = _non_empty_order_chunks(
            available_ro_orders,
            start=ro_start_order,
            end=ro_end_order,
            chunk_size=ro_chunk_size,
        )

    for batch_index, (start, end, expected_count) in enumerate(ro_ranges, start=1):
        filename = f"AquaNova_WAVE_V84_anchor_01_ro_nf_orders_{start:03d}_{end:03d}.json"
        cases = [
            _ro_order_range(
                f"V84_RO_NF_ORDERS_{start:03d}_{end:03d}",
                start,
                end,
                sheet=ro_sheet,
                expected_case_count=expected_count,
            )
        ]
        plans[filename] = _plan(
            name=f"V84 anchor 01.{batch_index:02d} - RO/NF Excel orders {start}-{end}",
            description=(
                "RO/NF WAVE anchor extraction from the experimental Excel matrix. "
                "This plan was preflighted to avoid empty order ranges."
            ),
            cases=cases,
            tier="anchor_ro_nf",
            ro_sheet=ro_sheet,
        )

    uf_flows = [70.0, 80.0, 90.0, 100.0, 110.0, 120.0, 130.0]
    plans["AquaNova_WAVE_V84_anchor_02_uf_flow_sweep.json"] = _plan(
        name="V84 anchor 02 - UF flow sweep",
        description="UF WAVE anchors for nonlinear TMP/backwash/CEB correction.",
        cases=[_uf_case(f"V84_UF_SFP2660_F{int(flow):03d}", flow=flow) for flow in uf_flows],
        tier="anchor_uf",
        ro_sheet=ro_sheet,
    )

    ccro_recovery_cases: list[dict[str, Any]] = []
    for rec in [80.0, 85.0, 90.0, 95.0]:
        ccro_recovery_cases.append(
            _ccro_case(
                f"V84_CCRO_1PASS_SOAR5000i_F100_R{int(rec):02d}",
                flow=100.0,
                pass_count=1,
                recovery=rec,
                tags=["recovery_sweep"],
            )
        )
    for rec in [85.0, 90.0]:
        ccro_recovery_cases.append(
            _ccro_case(
                f"V84_CCRO_2PASS_SOAR5000i_F100_P1R{int(rec):02d}_P2R{int(rec):02d}",
                flow=100.0,
                pass_count=2,
                recovery=rec,
                pass2_recovery=rec,
                tags=["recovery_sweep", "two_pass"],
            )
        )
    plans["AquaNova_WAVE_V84_anchor_03_ccro_recovery_sweep.json"] = _plan(
        name="V84 anchor 03 - CCRO recovery sweep",
        description="CCRO/HRRO WAVE anchors across R80/R85/R90/R95 and one/two-pass modes.",
        cases=ccro_recovery_cases,
        tier="anchor_ccro",
        ro_sheet=ro_sheet,
    )

    ccro_flow_cases: list[dict[str, Any]] = []
    for flow in [70.0, 85.0, 100.0, 115.0, 130.0]:
        ccro_flow_cases.append(
            _ccro_case(
                f"V84_CCRO_1PASS_SOAR5000i_F{int(flow):03d}_R90",
                flow=flow,
                pass_count=1,
                recovery=90.0,
                tags=["flow_sweep"],
            )
        )
    plans["AquaNova_WAVE_V84_anchor_04_ccro_flow_sweep.json"] = _plan(
        name="V84 anchor 04 - CCRO flow sweep",
        description="CCRO/HRRO WAVE anchors across feed-flow range at R90.",
        cases=ccro_flow_cases,
        tier="anchor_ccro",
        ro_sheet=ro_sheet,
    )

    # Stress anchors should be run after the stable batches.  Failures/warnings
    # are valuable labels for the nonlinear warning/correction model.
    stress_cases = [
        _ccro_case("V84_STRESS_CCRO_1PASS_SOAR5000i_F100_R95", flow=100.0, pass_count=1, recovery=95.0, tags=["stress", "high_recovery"]),
        _ccro_case("V84_STRESS_CCRO_2PASS_SOAR5000i_F100_P1R90_P2R95", flow=100.0, pass_count=2, recovery=90.0, pass2_recovery=95.0, tags=["stress", "two_pass"]),
        _uf_case("V84_STRESS_UF_SFP2660_F140", flow=140.0),
    ]
    plans["AquaNova_WAVE_V84_anchor_05_warning_stress_seeds.json"] = _plan(
        name="V84 anchor 05 - warning/stress seed cases",
        description=(
            "Small stress batch for warning-boundary labels.  Run after stable anchors; "
            "do not treat an individual WAVE warning as an automation failure unless PDF validation fails."
        ),
        cases=stress_cases,
        tier="anchor_stress",
        ro_sheet=ro_sheet,
    )

    return plans


def write_plans(output_dir: Path, plans: dict[str, dict[str, Any]]) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for filename, plan in plans.items():
        path = output_dir / filename
        path.write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def plan_summary(plans: dict[str, dict[str, Any]]) -> dict[str, Any]:
    counts: dict[str, int] = {}
    total = 0
    for plan in plans.values():
        for case in plan.get("cases", []):
            kind = str(case.get("kind", "unknown"))
            expected = int(case.get("expected_case_count") or 1)
            counts[kind] = counts.get(kind, 0) + expected
            total += expected
    return {"plan_count": len(plans), "case_count": total, "kind_counts": counts}


def remove_stale_v84_anchor_plans(output_dir: Path, keep_paths: Iterable[Path]) -> list[Path]:
    keep = {path.resolve() for path in keep_paths}
    removed: list[Path] = []
    for path in output_dir.glob("AquaNova_WAVE_V84_anchor_*.json"):
        if path.resolve() not in keep:
            path.unlink()
            removed.append(path)
    return removed


def _run_command_for_plan(path: Path) -> str:
    return (
        "python .\\scripts\\wave_records\\wave_video_demo.py `\n"
        f"  --run-production-plan \"{path}\" `\n"
        "  --production-max-attempts 2 `\n"
        "  --production-restart-monitor-index 2 `\n"
        "  --production-rerun-completed `\n"
        "  --allow-experimental-ro `\n"
        "  --allow-experimental-batch"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Export V84 WAVE nonlinear-calibration anchor campaign plans.")
    parser.add_argument("--output-dir", default=None, help="Directory for generated plan JSON files. Defaults to this script directory.")
    parser.add_argument("--ro-sheet", default=DEFAULT_RO_SHEET)
    parser.add_argument("--ro-start-order", type=int, default=1)
    parser.add_argument("--ro-end-order", type=int, default=45)
    parser.add_argument("--ro-chunk-size", type=int, default=10)
    parser.add_argument("--print-summary", action="store_true")
    parser.add_argument("--print-run-commands", action="store_true")
    parser.add_argument(
        "--no-ro-preflight",
        action="store_true",
        help="Disable Excel preflight and write fixed RO/NF order ranges. Normally leave this off.",
    )
    parser.add_argument(
        "--keep-stale-plans",
        action="store_true",
        help="Do not delete stale AquaNova_WAVE_V84_anchor_*.json files from earlier exports.",
    )
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    output_dir = Path(args.output_dir).resolve() if args.output_dir else script_dir
    available_ro_orders = None
    if not args.no_ro_preflight:
        excel_path = output_dir / EXCEL_MATRIX
        if not excel_path.exists():
            excel_path = script_dir / EXCEL_MATRIX
        available_ro_orders = _try_load_ro_case_orders(excel_path, args.ro_sheet)
        if available_ro_orders is not None:
            print(
                f"RO/NF preflight: sheet={args.ro_sheet} runnable_case_count={len(available_ro_orders)} "
                f"orders={available_ro_orders}"
            )
    plans = build_campaign_plans(
        ro_sheet=args.ro_sheet,
        ro_start_order=args.ro_start_order,
        ro_end_order=args.ro_end_order,
        ro_chunk_size=args.ro_chunk_size,
        available_ro_orders=available_ro_orders,
    )
    paths = write_plans(output_dir, plans)
    removed = [] if args.keep_stale_plans else remove_stale_v84_anchor_plans(output_dir, paths)
    print(f"V84 WAVE calibration campaign written: {len(paths)} plan file(s)")
    if removed:
        print(f"removed_stale_plan_count={len(removed)}")
        for path in removed:
            print(f"removed {path}")
    for path in paths:
        print(path)
    if args.print_summary:
        print("summary=" + json.dumps(plan_summary(plans), ensure_ascii=False, sort_keys=True))
    if args.print_run_commands:
        print("\nRun commands:")
        for path in paths:
            print("\n" + _run_command_for_plan(path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
