#!/usr/bin/env python3
"""Reusable production-plan builders for WAVE expansion kits.

The V70/V71 plan exporters started as quick one-off scripts and were almost
identical.  This module centralizes the plan-building primitives so future
expansion kits can add or adjust scenarios without copy/pasting another whole
exporter.

It is deliberately runtime-light: no pyautogui, Win32, WAVE, or pandas imports.
Plan exporters and selftests can import it safely on non-Windows machines.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping

SCHEMA_VERSION = 1
EXCEL_MATRIX = "AquaNova_WAVE_RO_NF_Experimental_Test_Matrix_V46_2026-07-03.xlsx"
NF_BASELINE_SHEET = "09_NF_BASELINE"
DEFAULT_UF_MODULE = "Ultrafiltration SFP-2660"
DEFAULT_WATER_PROFILE = "Well Water - Med Hardness"
DEFAULT_CCRO_ELEMENT = "FilmTec™ SOAR 5000i"


def common_defaults(*, version: str, restart_safe: bool = True, ro_sheet: str = NF_BASELINE_SHEET) -> dict[str, Any]:
    """Return defaults shared by generated production plans."""
    isolation_note = (
        "fresh_project_per_item=True prevents stale CCRO/UF topology from blocking later RO/NF cases."
        if restart_safe
        else "fresh_project_per_item=False reuses the current WAVE project; use only for intentionally coupled tests."
    )
    return {
        "allow_experimental_ro": True,
        "allow_experimental_batch": True,
        "fresh_project_per_item": bool(restart_safe),
        "ro_sheet": ro_sheet,
        "notes": f"Generated by wave_plan_library.py for {version}; run with V69+ runtime. {isolation_note}",
    }


def ro_order_range(plan_id: str, start: int, end: int, *, sheet: str = NF_BASELINE_SHEET) -> dict[str, Any]:
    return {
        "id": plan_id,
        "kind": "ro_excel",
        "path": EXCEL_MATRIX,
        "sheet": sheet,
        "start_order": int(start),
        "end_order": int(end),
        "allow_experimental_ro": True,
    }


def uf_case(case_id: str, *, flow: float = 100.0, module: str = DEFAULT_UF_MODULE) -> dict[str, Any]:
    return {
        "id": case_id,
        "kind": "uf_video",
        "uf_module": module,
        "uf_water_profile": DEFAULT_WATER_PROFILE,
        "uf_feed_flow": float(flow),
        "uf_pdf_name": f"{case_id}.pdf",
    }


def ccro_case(
    case_id: str,
    *,
    flow: float = 100.0,
    pass_count: int = 2,
    recovery: float = 90.0,
    pass2_recovery: float = 90.0,
) -> dict[str, Any]:
    case: dict[str, Any] = {
        "id": case_id,
        "kind": "ccro_video",
        "ccro_element": DEFAULT_CCRO_ELEMENT,
        "ccro_water_profile": DEFAULT_WATER_PROFILE,
        "ccro_feed_flow": float(flow),
        "ccro_pass_count": int(pass_count),
        "ccro_recovery": float(recovery),
        "ccro_pdf_name": f"{case_id}.pdf",
    }
    if int(pass_count) >= 2:
        case["ccro_pass2_recovery"] = float(pass2_recovery)
    return case


def production_plan(
    *,
    version: str,
    name: str,
    description: str,
    cases: list[dict[str, Any]],
    restart_safe: bool = True,
) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "name": name,
        "plan_kit_version": version,
        "description": description,
        # Top-level field is read first by wave_production._plan_requires_case_isolation.
        "fresh_project_per_item": bool(restart_safe),
        "defaults": common_defaults(version=version, restart_safe=restart_safe),
        "cases": cases,
    }


def build_standard_expansion_plans(
    *,
    version: str,
    file_prefix: str | None = None,
    restart_safe: bool = True,
    restart_suffix: bool = False,
) -> dict[str, dict[str, Any]]:
    """Build the three standard RO/NF→mixed expansion plans.

    Args:
        version: Human/version label embedded into case IDs and plan metadata.
        file_prefix: Optional filename version prefix. Defaults to ``version``.
        restart_safe: Whether generated plans should force a fresh WAVE project
            before each resolved production item.
        restart_suffix: Preserve the historical V71 filename suffix
            ``_restart_safe``.
    """
    fp = file_prefix or version
    suffix = "_restart_safe" if restart_suffix else ""
    v = str(version)
    return {
        f"AquaNova_WAVE_{fp}_production_plan_01_ro_nf_orders_1_3{suffix}.json": production_plan(
            version=v,
            name=f"{v} step 01 - RO/NF ladder orders 1-3" + (" restart-safe" if restart_safe else ""),
            description=(
                "First expansion after V69 smoke: first three NF baseline Excel orders. "
                "Forces a fresh WAVE project before every resolved RO/NF row."
                if restart_safe
                else "First three NF baseline Excel orders in the current project."
            ),
            restart_safe=restart_safe,
            cases=[ro_order_range("NF270_BASELINE_ORDERS_1_3", 1, 3)],
        ),
        f"AquaNova_WAVE_{fp}_production_plan_02_mixed_safe_5{suffix}.json": production_plan(
            version=v,
            name=f"{v} step 02 - mixed safe five" + (" restart-safe" if restart_safe else ""),
            description=(
                "Small mixed expansion: first two NF baseline orders plus one UF and two CCRO paths. "
                "Forces fresh isolation before every item."
            ),
            restart_safe=restart_safe,
            cases=[
                ro_order_range("NF270_BASELINE_ORDERS_1_2", 1, 2),
                uf_case(f"{v}_UF_SFP2660_F100", flow=100.0),
                ccro_case(f"{v}_CCRO_1PASS_SOAR5000i_F100_R85", flow=100.0, pass_count=1, recovery=85.0),
                ccro_case(f"{v}_CCRO_2PASS_SOAR5000i_F100_P1R90_P2R90", flow=100.0, pass_count=2, recovery=90.0, pass2_recovery=90.0),
            ],
        ),
        f"AquaNova_WAVE_{fp}_production_plan_03_mixed_8{suffix}.json": production_plan(
            version=v,
            name=f"{v} step 03 - mixed eight-ish" + (" restart-safe" if restart_safe else ""),
            description=(
                "Broader run: first four NF baseline orders plus two UF flow variants and two CCRO variants. "
                "Actual RO item count depends on the Excel rows present."
            ),
            restart_safe=restart_safe,
            cases=[
                ro_order_range("NF270_BASELINE_ORDERS_1_4", 1, 4),
                uf_case(f"{v}_UF_SFP2660_F080", flow=80.0),
                uf_case(f"{v}_UF_SFP2660_F100", flow=100.0),
                ccro_case(f"{v}_CCRO_1PASS_SOAR5000i_F100_R85", flow=100.0, pass_count=1, recovery=85.0),
                ccro_case(f"{v}_CCRO_2PASS_SOAR5000i_F100_P1R90_P2R90", flow=100.0, pass_count=2, recovery=90.0, pass2_recovery=90.0),
            ],
        ),
    }


def write_plan_files(plans: Mapping[str, dict[str, Any]], output_dir: Path | None = None) -> list[Path]:
    """Write filename -> payload mappings and return created paths."""
    target = output_dir or Path(__file__).resolve().parent
    target.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for filename, payload in plans.items():
        path = target / filename
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def print_export_summary(version: str, paths: list[Path]) -> None:
    print(f"{version} production plan kit written: {len(paths)} file(s)")
    for path in paths:
        print(path)
    if paths:
        print("\nRun dry-run validation with, for example:")
        print(f"python .\\scripts\\wave_records\\wave_video_demo.py --dry-run-production-plan \"{paths[0]}\"")
        print("\nThen run production with --production-restart-monitor-index 2.")


def build_v73_expansion_plans(
    *,
    version: str = "V73",
    file_prefix: str | None = None,
    restart_safe: bool = True,
    restart_suffix: bool = True,
) -> dict[str, dict[str, Any]]:
    """Build V73 plans, including the next cautious mixed expansion step.

    Step 04 intentionally grows from the already-passed V72 step 03 without
    changing the WAVE runtime: add one UF flow point and one extra CCRO 1-pass
    recovery point while keeping fresh-project isolation enabled.
    """
    plans = build_standard_expansion_plans(
        version=version,
        file_prefix=file_prefix,
        restart_safe=restart_safe,
        restart_suffix=restart_suffix,
    )
    fp = file_prefix or version
    suffix = "_restart_safe" if restart_suffix else ""
    v = str(version)
    plans[f"AquaNova_WAVE_{fp}_production_plan_04_mixed_10_cautious{suffix}.json"] = production_plan(
        version=v,
        name=f"{v} step 04 - mixed ten-ish cautious" + (" restart-safe" if restart_safe else ""),
        description=(
            "Next expansion after the V72 seven-item success: broader NF baseline range, "
            "three UF flow variants, and three CCRO variants.  The resolved RO count still "
            "depends on available Excel rows; fresh isolation is forced before every item."
        ),
        restart_safe=restart_safe,
        cases=[
            ro_order_range("NF270_BASELINE_ORDERS_1_5", 1, 5),
            uf_case(f"{v}_UF_SFP2660_F080", flow=80.0),
            uf_case(f"{v}_UF_SFP2660_F100", flow=100.0),
            uf_case(f"{v}_UF_SFP2660_F120", flow=120.0),
            ccro_case(f"{v}_CCRO_1PASS_SOAR5000i_F100_R80", flow=100.0, pass_count=1, recovery=80.0),
            ccro_case(f"{v}_CCRO_1PASS_SOAR5000i_F100_R85", flow=100.0, pass_count=1, recovery=85.0),
            ccro_case(f"{v}_CCRO_2PASS_SOAR5000i_F100_P1R90_P2R90", flow=100.0, pass_count=2, recovery=90.0, pass2_recovery=90.0),
        ],
    )
    return plans


__all__ = [name for name in globals() if not name.startswith("_")]
