#!/usr/bin/env python3
"""Static WAVE coordinate calibration data.

This module intentionally contains no Win32/pyautogui imports.  Keeping the
large coordinate tables here makes wave_common.py focused on shared types,
constants, dependencies, and application state while preserving the public names
re-exported through wave_common.
"""
from __future__ import annotations

DEFAULT_POINTS: dict[str, tuple[int, int]] = {
    "wave_titlebar": (600, 18),
    "configuration_ribbon_tab": (160, 60),
    "add_case": (356, 106),
    "feed_setup_tab": (474, 60),
    "open_water_library": (112, 165),
    "adjust_all_ions": (824, 125),
    "feed_temp_min": (956, 359),
    "feed_temp_design": (1056, 359),
    "feed_temp_max": (1154, 359),
    "home_tab": (36, 226),
    "home_feed_flow": (244, 550),
    "ro_icon": (1045, 447),
    "uf_icon": (1045, 354),
    "ccro_icon": (1110, 447),
    "process_drop_point": (385, 534),
    "reverse_osmosis_tab": (220, 226),
    "ultrafiltration_tab": (210, 226),
    "ccro_tab": (194, 226),
    "stage_1_radio": (184, 345),
    "stage_2_radio": (229, 345),
    "stage_3_radio": (275, 345),
    "stage_4_radio": (321, 345),
    "stage_5_radio": (366, 345),
    "add_pass": (48, 345),
    "pass_1_tab": (58, 306),
    "pass_2_tab": (58, 339),
    "ro_flow_factor": (383, 405),
    "ro_pass_back_pressure": (383, 495),
    "add_chemicals_degas": (431, 90),
    "compaction": (616, 90),
    "ro_toc_rejection": (616, 128),
    "ro_feed_flow": (706, 315),
    "ro_recovery": (706, 350),
    "ro_temperature_mode": (337, 449),
    "ro_temperature_value": (383, 449),
    "pv_per_stage": (484, 600),
    "elements_per_pv": (484, 635),
    "element_type_combo": (480, 666),
    "stage_back_pressure_row": (480, 786),
    "stage_boost_pressure_row": (480, 821),
    "stage_flow_factor_row": (480, 921),
    "summary_report_tab": (315, 226),
    "report_ribbon_tab": (596, 60),
    "export_to_pdf": (740, 124),
    "report_temperature_value": (420, 164),
    # V55 UF video-derived controls. Coordinates are in the same 1280x1032 WAVE reference frame.
    "uf_design_nav": (86, 306),
    "uf_configuration_nav": (86, 332),
    "uf_backwash_nav": (86, 356),
    "uf_more_nav": (86, 382),
    "uf_feed_flow_auto": (358, 337),
    "uf_strainer_recovery": (360, 448),
    "uf_strainer_size": (360, 482),
    "uf_design_module_combo": (456, 593),
    "uf_config_module_combo": (451, 540),
    "uf_online_trains": (913, 368),
    "uf_standby_trains": (913, 403),
    "uf_redundant_trains": (913, 438),
    "uf_modules_per_train": (913, 513),
    # V55 UF Backwash / CEB / CIP controls from the 2026-07-06 video run inventory.
    "uf_ceb_nav": (86, 382),
    "uf_cip_nav": (86, 410),
    "uf_additional_settings_nav": (86, 438),
    "uf_backwash_water_type_combo": (1041, 340),
    "uf_forward_flush_water_type_combo": (1041, 381),
    "uf_backwash_protocol_combo": (1041, 472),
    "uf_bw_air_scour_sec": (1175, 703),
    "uf_bw_drain_sec": (1175, 740),
    "uf_bw_top_backwash_sec": (1175, 777),
    "uf_bw_bottom_backwash_sec": (1175, 812),
    "uf_bw_forward_flush_sec": (1175, 849),
    "uf_bw_between_air_scour": (1175, 897),
    "uf_ceb_water_type_combo": (1056, 337),
    "uf_ceb_mineral_acid_combo": (264, 486),
    "uf_ceb_mineral_acid_ph": (264, 536),
    "uf_ceb_alkali_combo": (663, 486),
    "uf_ceb_alkali_ph": (657, 536),
    "uf_ceb_lsi": (1074, 544),
    "uf_ceb_air_scour_sec": (1175, 718),
    "uf_ceb_drain_sec": (1175, 754),
    "uf_ceb_top_backwash_sec": (1175, 793),
    "uf_ceb_bottom_backwash_sec": (1175, 829),
    "uf_ceb_forward_flush_sec": (1175, 865),
    "uf_ceb_chemical_soak_min": (1175, 909),
}

CONTROL_FALLBACK_OFFSETS: dict[str, list[tuple[int, int]]] = {
    "open_water_library": [(0, 0), (-34, 0), (34, 0), (0, -12), (0, 12)],
}

CALIBRATION_ORDER = [
    ("wave_titlebar", "WAVE 제목 표시줄의 빈 곳"),
    ("configuration_ribbon_tab", "상단 Configuration 리본 탭"),
    ("add_case", "Configuration 리본의 Add Case 버튼"),
    ("feed_setup_tab", "상단 Feed Setup 탭"),
    ("open_water_library", "Open Water Library 버튼"),
    ("adjust_all_ions", "Feed Setup 리본의 Adjust All Ions 버튼"),
    ("feed_temp_min", "Feed Water 화면의 Minimum 온도 입력칸"),
    ("feed_temp_design", "Feed Water 화면의 Design 온도 입력칸"),
    ("feed_temp_max", "Feed Water 화면의 Maximum 온도 입력칸"),
    ("home_tab", "하단 Home 탭"),
    ("home_feed_flow", "Home 화면 Feed Water 유량 입력칸"),
    ("ro_icon", "Technologies의 초록색 RO 아이콘"),
    ("uf_icon", "Technologies의 주황색 UF 아이콘"),
    ("ccro_icon", "Technologies의 노란색 CCRO 아이콘"),
    ("process_drop_point", "두 화살표 사이의 회색 공정 드롭 지점"),
    ("reverse_osmosis_tab", "하단 Reverse Osmosis 탭"),
    ("ultrafiltration_tab", "하단 Ultrafiltration 탭"),
    ("ccro_tab", "하단 CCRO 탭"),
    ("stage_1_radio", "Number of Stages의 1 라디오 버튼"),
    ("stage_2_radio", "Number of Stages의 2 라디오 버튼"),
    ("stage_3_radio", "Number of Stages의 3 라디오 버튼"),
    ("stage_4_radio", "Number of Stages의 4 라디오 버튼"),
    ("stage_5_radio", "Number of Stages의 5 라디오 버튼"),
    ("add_pass", "RO 화면 Add Pass 링크"),
    ("pass_1_tab", "RO 화면 Pass 1 선택 버튼"),
    ("pass_2_tab", "RO 화면 Pass 2 선택 버튼"),
    ("ro_flow_factor", "RO 화면 Flow Factor 입력칸"),
    ("ro_pass_back_pressure", "RO 화면 Pass Permeate Back Pressure 입력칸"),
    ("add_chemicals_degas", "Configuration 리본 Add Chemicals/Degas 버튼"),
    ("compaction", "Configuration 리본 Compaction 버튼"),
    ("ro_toc_rejection", "Configuration 리본 RO TOC Rejection 버튼"),
    ("ro_feed_flow", "RO 화면 Feed Flow 입력칸"),
    ("ro_recovery", "RO 화면 Recovery 입력칸"),
    ("ro_temperature_mode", "RO 화면 Temperature 모드 드롭다운"),
    ("ro_temperature_value", "RO 화면 Temperature 숫자 입력칸"),
    ("pv_per_stage", "# PV per stage 값 셀"),
    ("elements_per_pv", "# Els per PV 값 셀"),
    ("element_type_combo", "Element Type 드롭다운"),
    ("stage_back_pressure_row", "Stage Back Press 행의 Stage 1 셀"),
    ("stage_boost_pressure_row", "Boost Press 행의 Stage 1 셀"),
    ("stage_flow_factor_row", "Stage Flow Factor 행의 Stage 1 셀"),
    ("summary_report_tab", "하단 Summary Report 탭"),
    ("report_ribbon_tab", "상단 Report 리본 탭"),
    ("export_to_pdf", "Export to PDF 버튼"),
    ("report_temperature_value", "Report 리본 Temperature 숫자 입력칸"),
]


__all__ = ["DEFAULT_POINTS", "CONTROL_FALLBACK_OFFSETS", "CALIBRATION_ORDER"]
